#include "Bee.h"




void Bee::BeeAppeard()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:0000000000000A1D begin
{
}
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:0000000000000A1D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
