#include "Controller.h"




void Controller::EncreasePower()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009E2 begin
{
}
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009E2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Controller::ReduceEngine()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009E4 begin
{
}
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009E4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Controller::ConstPower()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009E6 begin
{
}
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009E6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
