#include "EngineController.h"




void EngineController::SetEnginePower()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:0000000000000A12 begin
{
}
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:0000000000000A12 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
