#include "Height sensor.h"




void Height sensor::SensorHeight()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009D5 begin
{
}
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009D5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
