#include "Puch.h"




void Puch::SetHeight()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009D7 begin
{
}
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009D7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Puch::Land()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009D9 begin
{
}
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009D9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Puch::EmergencyLanding()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009DB begin
{
}
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009DB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Puch::HoldAltitude()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009DD begin
{
}
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009DD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Puch::TakeHoney()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009E8 begin
{
}
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009E8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Puch::StartFly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009EC begin
{
}
// section -64--88-1-35--36756cd1:177aa3758d5:-8000:00000000000009EC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
